# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giao_dien_02.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class giao_dien(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1427, 964)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 1401, 901))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgba(230, 240, 255, 255);\n"
"")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 181, 901))
        self.widget_2.setStyleSheet("background-color:rgba(0, 0, 127, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.383, y1:0, x2:0.462687, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(0, 0, 127, 100));")
        self.widget_2.setObjectName("widget_2")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(30, 140, 121, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.logo = QtWidgets.QLabel(self.widget_2)
        self.logo.setGeometry(QtCore.QRect(10, 10, 171, 121))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(r"C:\Users\TRAN_NGOC_HAN\Desktop\BAO_CAO_XU_LY_ANH\MAIN_BAO_CAO\Tomato_carrot_main\UTC2.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.ca_chua = QtWidgets.QPushButton(self.widget_2)
        self.ca_chua.setGeometry(QtCore.QRect(-20, 180, 191, 61))
        self.ca_chua.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.ca_chua.setObjectName("ca_chua")
        self.ca_rot = QtWidgets.QPushButton(self.widget_2)
        self.ca_rot.setGeometry(QtCore.QRect(-20, 260, 191, 61))
        self.ca_rot.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.ca_rot.setObjectName("ca_rot")
        self.tang_tuong_phan = QtWidgets.QPushButton(self.widget_2)
        self.tang_tuong_phan.setGeometry(QtCore.QRect(-20, 340, 191, 61))
        self.tang_tuong_phan.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.tang_tuong_phan.setObjectName("tang_tuong_phan")
        self.giam_tuong_phan = QtWidgets.QPushButton(self.widget_2)
        self.giam_tuong_phan.setGeometry(QtCore.QRect(-20, 420, 191, 61))
        self.giam_tuong_phan.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.giam_tuong_phan.setObjectName("giam_tuong_phan")
        self.do_sang_tang = QtWidgets.QPushButton(self.widget_2)
        self.do_sang_tang.setGeometry(QtCore.QRect(-20, 500, 191, 61))
        self.do_sang_tang.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.do_sang_tang.setObjectName("do_sang_tang")
        self.do_sang_giam = QtWidgets.QPushButton(self.widget_2)
        self.do_sang_giam.setGeometry(QtCore.QRect(-20, 580, 191, 61))
        self.do_sang_giam.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.do_sang_giam.setObjectName("do_sang_giam")
        self.do_mo_tang = QtWidgets.QPushButton(self.widget_2)
        self.do_mo_tang.setGeometry(QtCore.QRect(-20, 660, 191, 61))
        self.do_mo_tang.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.do_mo_tang.setObjectName("do_mo_tang")
        self.do_mo_giam = QtWidgets.QPushButton(self.widget_2)
        self.do_mo_giam.setGeometry(QtCore.QRect(-20, 740, 191, 61))
        self.do_mo_giam.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.do_mo_giam.setObjectName("do_mo_giam")
        self.bao_vien = QtWidgets.QPushButton(self.widget_2)
        self.bao_vien.setGeometry(QtCore.QRect(-20, 820, 191, 61))
        self.bao_vien.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.bao_vien.setObjectName("bao_vien")
        self.chup_hinh = QtWidgets.QPushButton(self.widget)
        self.chup_hinh.setGeometry(QtCore.QRect(500, 490, 311, 71))
        self.chup_hinh.setStyleSheet("background-color: rgba(0, 0, 127, 255);\n"
"color: #ffffff;          /* Màu chữ */\n"
"font-size: 16px;         /* Kích thước chữ */\n"
"font-family: \"Arial\";    /* Kiểu font */\n"
"font-weight: bold;       /* Độ đậm */\n"
"border-radius: 10;\n"
"")
        self.chup_hinh.setObjectName("chup_hinh")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 10, 631, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.video_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.video_1.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.video_1.setContentsMargins(0, 0, 0, 0)
        self.video_1.setObjectName("video_1")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(830, 10, 371, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.video_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.video_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video_2.setContentsMargins(0, 0, 0, 0)
        self.video_2.setObjectName("video_2")
        self.camera = QtWidgets.QPushButton(self.widget)
        self.camera.setGeometry(QtCore.QRect(190, 490, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setStyleSheet("background-color: rgba(0, 0, 127, 255);\n"
"color:#ffd10e;          /* Màu chữ */\n"
"font-size: 16px;         /* Kích thước chữ */\n"
"font-family: \"Arial\";    /* Kiểu font */\n"
"font-weight: bold;       /* Độ đậm */\n"
"border-radius: 13;")
        self.camera.setObjectName("camera")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(1220, 10, 181, 901))
        self.widget_3.setStyleSheet("background-color:rgba(0, 0, 127, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.383, y1:0, x2:0.462687, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(0, 0, 127, 100));")
        self.widget_3.setObjectName("widget_3")
        self.tang_iterations = QtWidgets.QPushButton(self.widget_3)
        self.tang_iterations.setGeometry(QtCore.QRect(10, 410, 191, 61))
        self.tang_iterations.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.tang_iterations.setObjectName("tang_iterations")
        self.giam_iterations = QtWidgets.QPushButton(self.widget_3)
        self.giam_iterations.setGeometry(QtCore.QRect(10, 490, 191, 61))
        self.giam_iterations.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.giam_iterations.setObjectName("giam_iterations")
        self.hoi_tu = QtWidgets.QPushButton(self.widget_3)
        self.hoi_tu.setGeometry(QtCore.QRect(10, 250, 191, 61))
        self.hoi_tu.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.hoi_tu.setObjectName("hoi_tu")
        self.gian_no = QtWidgets.QPushButton(self.widget_3)
        self.gian_no.setGeometry(QtCore.QRect(10, 330, 191, 61))
        self.gian_no.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.gian_no.setObjectName("gian_no")
        self.Do = QtWidgets.QPushButton(self.widget_3)
        self.Do.setGeometry(QtCore.QRect(10, 570, 191, 61))
        self.Do.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.Do.setObjectName("Do")
        self.Cam = QtWidgets.QPushButton(self.widget_3)
        self.Cam.setGeometry(QtCore.QRect(10, 650, 191, 61))
        self.Cam.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.Cam.setObjectName("Cam")
        self.tat_cai_dat = QtWidgets.QPushButton(self.widget_3)
        self.tat_cai_dat.setGeometry(QtCore.QRect(10, 730, 191, 61))
        self.tat_cai_dat.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.tat_cai_dat.setObjectName("tat_cai_dat")
        self.thoat = QtWidgets.QPushButton(self.widget_3)
        self.thoat.setGeometry(QtCore.QRect(10, 810, 191, 61))
        self.thoat.setStyleSheet("\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: #000000;          /* Màu chữ */\n"
"    font-size: 13px;         /* Kích thước chữ */\n"
"    font-family: \"Arial\";    /* Kiểu font */\n"
"    font-weight: bold;       /* Độ đậm */\n"
"    border-radius: 20;")
        self.thoat.setObjectName("thoat")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 141, 221))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 127, 0);\n"
"color: #ffd10e;  ")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(830, 310, 371, 291))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.video_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.video_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video_3.setContentsMargins(0, 0, 0, 0)
        self.video_3.setObjectName("video_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(830, 610, 371, 291))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.video_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.video_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video_4.setContentsMargins(0, 0, 0, 0)
        self.video_4.setObjectName("video_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(190, 570, 631, 331))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.video_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.video_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video_5.setContentsMargins(0, 0, 0, 0)
        self.video_5.setObjectName("video_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1427, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ca_chua.setText(_translate("MainWindow", "CÀ CHUA"))
        self.ca_rot.setText(_translate("MainWindow", "CARROT"))
        self.tang_tuong_phan.setText(_translate("MainWindow", "TƯƠNG PHẢN TĂNG"))
        self.giam_tuong_phan.setText(_translate("MainWindow", "TƯƠNG PHẢN GIẢM"))
        self.do_sang_tang.setText(_translate("MainWindow", "ĐỘ SÁNG TĂNG"))
        self.do_sang_giam.setText(_translate("MainWindow", "ĐỘ SÁNG GIẢM"))
        self.do_mo_tang.setText(_translate("MainWindow", "ĐỘ MỜ TĂNG"))
        self.do_mo_giam.setText(_translate("MainWindow", "ĐỘ MỜ GIẢM"))
        self.bao_vien.setText(_translate("MainWindow", "BAO VIỀN"))
        self.chup_hinh.setText(_translate("MainWindow", "CHỤP ẢNH"))
        self.camera.setText(_translate("MainWindow", "CAMERA"))
        self.tang_iterations.setText(_translate("MainWindow", "TĂNG ITERATIONS"))
        self.giam_iterations.setText(_translate("MainWindow", "GIẢM ITERATIONS"))
        self.hoi_tu.setText(_translate("MainWindow", "HỘI TỤ"))
        self.gian_no.setText(_translate("MainWindow", "GIÃN NỞ"))
        self.Do.setText(_translate("MainWindow", "ĐỎ"))
        self.Cam.setText(_translate("MainWindow", "CAM"))
        self.tat_cai_dat.setText(_translate("MainWindow", "TẮT CÀI ĐẶT"))
        self.thoat.setText(_translate("MainWindow", "THOÁT"))
        self.label_3.setText(_translate("MainWindow", "U \n"
"T \n"
"C \n"
"2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = giao_dien()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
