# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GIAO_DIEN_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_01(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 828)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 1024, 751))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgba(250, 250, 255, 255);\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 61))
        self.label.setStyleSheet("background-color: rgba(0, 0, 127, 180);\n"
"border-radius: 5px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r'C:\Users\TRAN_NGOC_HAN\Desktop\BAO_CAO_XU_LY_ANH\CODE\UTC2.png'))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(-10, 110, 1031, 641))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(r'C:\Users\TRAN_NGOC_HAN\Desktop\BAO_CAO_XU_LY_ANH\MAIN_BAO_CAO\Tomato_carrot_main\Phong_canh_UTC2.jpg'))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 120, 1031, 631))
        self.widget_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 0, 180), stop:1 rgba(255, 255, 255, 0));\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(280, 30, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #000000;\n"
"border-color: #000000;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(220, 110, 611, 441))
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.462, x2:0.985075, y2:0.864, stop:0 rgba(0, 0, 0, 170), stop:1 rgba(255, 255, 255, 100));\n"
"border-radius: 25px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(140, 80, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #ffffff;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(140, 120, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #ffffff;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(170, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #ffffff;")
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(160, 230, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 230);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 330, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0); /* Màu đỏ với độ trong suốt */\n"
"color: #ffff00;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.widget_3.raise_()
        self.label_3.raise_()
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(390, 110, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.name_UTC2 = QtWidgets.QLabel(self.widget)
        self.name_UTC2.setGeometry(QtCore.QRect(10, 10, 1001, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.name_UTC2.setFont(font)
        self.name_UTC2.setMouseTracking(False)
        self.name_UTC2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.447761 rgba(33, 0, 135, 255), stop:1 rgba(33, 0, 135, 150)) ; /* Màu đỏ với độ trong suốt */\n"
"color: #FFFFFF;\n"
"border-radius: 20px; /* Bo tròn 5 pixel */\n"
"")
        self.name_UTC2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_UTC2.setObjectName("name_UTC2")
        self.label_6.raise_()
        self.name_UTC2.raise_()
        self.label.raise_()
        self.widget_2.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "BÁO CÁO BÀI TẬP LỚN MÔN XỬ LÝ ẢNH"))
        self.label_7.setText(_translate("MainWindow", "Giảng viên hướng dẫn:  MAI VẠN HẬU"))
        self.label_8.setText(_translate("MainWindow", "Sinh viên thực hiện: TRẦN NGỌC HÂN"))
        self.label_9.setText(_translate("MainWindow", "Mã số sinh viên:  6351030024"))
        self.pushButton.setText(_translate("MainWindow", "BẮT ĐẦU"))
        self.pushButton_2.setText(_translate("MainWindow", "THOÁT"))
        self.label_4.setText(_translate("MainWindow", "ỨNG DỤNG CÔNG NGHỆ XỬ LÝ ẢNH \n"
" ĐỂ NHẬN DẠNG CÀ CHUA CÀ ROT TỪ CAMERA"))
        self.label_5.setText(_translate("MainWindow", "BỘ MÔN ĐIỆN - ĐIỆN TỬ"))
        self.name_UTC2.setText(_translate("MainWindow", "TRƯỜNG ĐẠI HỌC GIAO THÔNG VẬN TẢI - PHÂN HIỆU TẠI THÀNH PHỐ HỒ CHÍ MINH \n"
"   UNIVERSITY OF TRANSPORT AND COMMUNICATIONS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_01()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
